// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileNode represents a single entry in the directory tree.
 */
export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileNode[] | undefined}
             */
            this["children"] = undefined;
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

/**
 * GrepMatch represents a single search hit.
 */
export class GrepMatch {
    /**
     * Creates a new GrepMatch instance.
     * @param {Partial<GrepMatch>} [$$source = {}] - The source object to create the GrepMatch.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("lineNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineNumber"] = 0;
        }
        if (!("lineText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lineText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrepMatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GrepMatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GrepMatch(/** @type {Partial<GrepMatch>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
