// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes file system operations to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFile creates an empty file at the given path, creating parent directories as needed.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function CreateFile(path) {
    return $Call.ByID(305703475, path);
}

/**
 * DeleteFile removes a file or recursively removes a directory.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path) {
    return $Call.ByID(1926458868, path);
}

/**
 * FileExists reports whether the given path exists.
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(2410812523, path);
}

/**
 * GetDirectoryTree returns the full recursive directory tree (max depth 10).
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileNode>}
 */
export function GetDirectoryTree(path) {
    return $Call.ByID(3779728218, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetWorkingDirectory returns the process working directory.
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkingDirectory() {
    return $Call.ByID(2996376285);
}

/**
 * GrepFiles searches all text files under rootPath for query (case-insensitive)
 * using a parallel worker pool. Returns up to maxResults matches.
 * @param {string} rootPath
 * @param {string} query
 * @param {number} maxResults
 * @returns {$CancellablePromise<$models.GrepMatch[]>}
 */
export function GrepFiles(rootPath, query, maxResults) {
    return $Call.ByID(1800544500, rootPath, query, maxResults).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListDirectory returns a flat list of entries one level deep.
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListDirectory(path) {
    return $Call.ByID(3016498900, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MkDir creates a directory (and all parents) at the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function MkDir(path) {
    return $Call.ByID(1188792528, path);
}

/**
 * ReadFile reads a file and returns its content as a string.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(917937179, path);
}

/**
 * ReadFileAsBase64 reads a binary file and returns its content as a base64-encoded string.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileAsBase64(path) {
    return $Call.ByID(1273734528, path);
}

/**
 * RenameFile renames (or moves) a file or directory from oldPath to newPath.
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(oldPath, newPath) {
    return $Call.ByID(3814548421, oldPath, newPath);
}

/**
 * SelectDirectory opens a native folder-picker dialog and returns the chosen path.
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(2634166840);
}

/**
 * SelectFile opens a native file-picker dialog and returns the chosen file path.
 * extensions is a comma-separated list like "db,sqlite,sqlite3" (without dots).
 * @param {string} title
 * @param {string} extensions
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile(title, extensions) {
    return $Call.ByID(1346128595, title, extensions);
}

/**
 * SetWorkingDirectory changes the active project root.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkingDirectory(path) {
    return $Call.ByID(2119850697, path);
}

/**
 * WriteFile writes content to the given path, creating directories as needed.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, content) {
    return $Call.ByID(1365434050, path, content);
}

// Private type creation functions
const $$createType0 = $models.FileNode.createFrom;
const $$createType1 = $models.GrepMatch.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
