// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BranchInfo represents a git branch.
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isCurrent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCurrent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

/**
 * CommitFileInfo describes one file changed in a commit.
 */
export class CommitFileInfo {
    /**
     * Creates a new CommitFileInfo instance.
     * @param {Partial<CommitFileInfo>} [$$source = {}] - The source object to create the CommitFileInfo.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitFileInfo(/** @type {Partial<CommitFileInfo>} */($$parsedSource));
    }
}

/**
 * CommitInfo is a trimmed representation of a commit.
 */
export class CommitInfo {
    /**
     * Creates a new CommitInfo instance.
     * @param {Partial<CommitInfo>} [$$source = {}] - The source object to create the CommitInfo.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("when" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["when"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo(/** @type {Partial<CommitInfo>} */($$parsedSource));
    }
}

/**
 * FileStatus represents one entry from `git status`.
 */
export class FileStatus {
    /**
     * Creates a new FileStatus instance.
     * @param {Partial<FileStatus>} [$$source = {}] - The source object to create the FileStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("staging" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["staging"] = "";
        }
        if (!("worktree" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worktree"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStatus(/** @type {Partial<FileStatus>} */($$parsedSource));
    }
}

/**
 * RepoStatus summarises the working-tree state.
 */
export class RepoStatus {
    /**
     * Creates a new RepoStatus instance.
     * @param {Partial<RepoStatus>} [$$source = {}] - The source object to create the RepoStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {FileStatus[]}
             */
            this["files"] = [];
        }
        if (!("isDirty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        return new RepoStatus(/** @type {Partial<RepoStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
