// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes git operations to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckoutBranch switches to the specified branch.
 * @param {string} repoPath
 * @param {string} branchName
 * @returns {$CancellablePromise<void>}
 */
export function CheckoutBranch(repoPath, branchName) {
    return $Call.ByID(3848571646, repoPath, branchName);
}

/**
 * Commit creates a new commit with the provided message.
 * @param {string} path
 * @param {string} message
 * @param {string} authorName
 * @param {string} authorEmail
 * @returns {$CancellablePromise<string>}
 */
export function Commit(path, message, authorName, authorEmail) {
    return $Call.ByID(4072012295, path, message, authorName, authorEmail);
}

/**
 * DiscardFile discards working-tree changes for a file (git checkout -- <file>).
 * For untracked files it removes the file entirely.
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DiscardFile(repoPath, filePath) {
    return $Call.ByID(3055670330, repoPath, filePath);
}

/**
 * GetBranches returns all local branches.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.BranchInfo[]>}
 */
export function GetBranches(repoPath) {
    return $Call.ByID(131204430, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCommitFileDiff returns the unified diff of a single file at the given commit.
 * @param {string} repoPath
 * @param {string} hash
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetCommitFileDiff(repoPath, hash, filePath) {
    return $Call.ByID(626562738, repoPath, hash, filePath);
}

/**
 * GetCommitFiles returns the list of files changed in a given commit.
 * @param {string} repoPath
 * @param {string} hash
 * @returns {$CancellablePromise<$models.CommitFileInfo[]>}
 */
export function GetCommitFiles(repoPath, hash) {
    return $Call.ByID(1024275706, repoPath, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetFileDiff returns a unified diff string for the given file.
 * For tracked files it shows unstaged changes (falling back to staged).
 * For untracked files it shows the full content as additions.
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetFileDiff(repoPath, filePath) {
    return $Call.ByID(239103655, repoPath, filePath);
}

/**
 * GetHeadFileContent returns the content of a file at HEAD (last commit).
 * Returns an empty string if the file is untracked (no HEAD version).
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetHeadFileContent(repoPath, filePath) {
    return $Call.ByID(2955441447, repoPath, filePath);
}

/**
 * GetLog returns the last N commits.
 * @param {string} path
 * @param {number} limit
 * @returns {$CancellablePromise<$models.CommitInfo[]>}
 */
export function GetLog(path, limit) {
    return $Call.ByID(603502156, path, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetStatus returns the current working-tree status.
 * @param {string} path
 * @returns {$CancellablePromise<$models.RepoStatus>}
 */
export function GetStatus(path) {
    return $Call.ByID(1157714504, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * InitRepo initialises a new git repository at the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function InitRepo(path) {
    return $Call.ByID(1286318204, path);
}

/**
 * RestoreFileFromCommit restores a single file to its state at the given commit.
 * @param {string} repoPath
 * @param {string} hash
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFileFromCommit(repoPath, hash, filePath) {
    return $Call.ByID(1649409247, repoPath, hash, filePath);
}

/**
 * RevertCommit creates a new commit that undoes the changes introduced by the given commit hash.
 * @param {string} repoPath
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RevertCommit(repoPath, hash) {
    return $Call.ByID(3658561145, repoPath, hash);
}

/**
 * StageAll stages all changes (equivalent to `git add -A`).
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function StageAll(path) {
    return $Call.ByID(1163917983, path);
}

/**
 * StageFile stages a single file (git add -- <file>).
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function StageFile(repoPath, filePath) {
    return $Call.ByID(4195949458, repoPath, filePath);
}

/**
 * UnstageFile removes a file from the staging area (git restore --staged -- <file>).
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function UnstageFile(repoPath, filePath) {
    return $Call.ByID(602278151, repoPath, filePath);
}

// Private type creation functions
const $$createType0 = $models.BranchInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CommitFileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.CommitInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.RepoStatus.createFrom;
