// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages database connections and exposes operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect opens a connection using the given config, stores it, and returns its ID.
 * @param {$models.ConnectionConfig} cfg
 * @returns {$CancellablePromise<$models.ConnectionInfo>}
 */
export function Connect(cfg) {
    return $Call.ByID(2475514295, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DescribeTable returns column information for the given table.
 * @param {string} connID
 * @param {string} tableName
 * @returns {$CancellablePromise<$models.ColumnInfo[]>}
 */
export function DescribeTable(connID, tableName) {
    return $Call.ByID(1358485394, connID, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Disconnect closes and removes a connection by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(id) {
    return $Call.ByID(634087817, id);
}

/**
 * ListConnections returns all active connections.
 * @returns {$CancellablePromise<$models.ConnectionInfo[]>}
 */
export function ListConnections() {
    return $Call.ByID(3475704024).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListTables returns the tables (and views) in the connected database.
 * @param {string} connID
 * @returns {$CancellablePromise<$models.TableInfo[]>}
 */
export function ListTables(connID) {
    return $Call.ByID(2462127514, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RunQuery executes a SQL query and returns up to maxRows rows.
 * @param {string} connID
 * @param {string} query
 * @param {number} maxRows
 * @returns {$CancellablePromise<$models.QueryResult>}
 */
export function RunQuery(connID, query, maxRows) {
    return $Call.ByID(908986624, connID, query, maxRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ConnectionInfo.createFrom;
const $$createType1 = $models.ColumnInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $models.TableInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.QueryResult.createFrom;
