// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages the terminal PTY WebSocket server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * StartAndGetPort starts the WebSocket PTY server (idempotent) and returns the port.
 * @returns {$CancellablePromise<number>}
 */
export function StartAndGetPort() {
    return $Call.ByID(137778820);
}
