// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * AgentRunResult holds the result of an agent run.
 */
export class AgentRunResult {
    /**
     * Creates a new AgentRunResult instance.
     * @param {Partial<AgentRunResult>} [$$source = {}] - The source object to create the AgentRunResult.
     */
    constructor($$source = {}) {
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {Message[]}
             */
            this["messages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agentType"] = undefined;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RalphLoopResult | null | undefined}
             */
            this["ralphResult"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        if ("ralphResult" in $$parsedSource) {
            $$parsedSource["ralphResult"] = $$createField6_0($$parsedSource["ralphResult"]);
        }
        return new AgentRunResult(/** @type {Partial<AgentRunResult>} */($$parsedSource));
    }
}

export const Message = types$0.Message;

/**
 * @typedef {types$0.Message} Message
 */

export const RalphLoopResult = types$0.RalphLoopResult;

/**
 * @typedef {types$0.RalphLoopResult} RalphLoopResult
 */

// Private type creation functions
const $$createType0 = types$0.Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.RalphLoopResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
