// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Script represents a saved Playwright script.
 */
export class Script {
    /**
     * Creates a new Script instance.
     * @param {Partial<Script>} [$$source = {}] - The source object to create the Script.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Script instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Script}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Script(/** @type {Partial<Script>} */($$parsedSource));
    }
}

/**
 * TestRunResult holds structured test results.
 */
export class TestRunResult {
    /**
     * Creates a new TestRunResult instance.
     * @param {Partial<TestRunResult>} [$$source = {}] - The source object to create the TestRunResult.
     */
    constructor($$source = {}) {
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rawOutput"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TestSuite[] | undefined}
             */
            this["suites"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TestStats | null | undefined}
             */
            this["stats"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("suites" in $$parsedSource) {
            $$parsedSource["suites"] = $$createField3_0($$parsedSource["suites"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField4_0($$parsedSource["stats"]);
        }
        return new TestRunResult(/** @type {Partial<TestRunResult>} */($$parsedSource));
    }
}

/**
 * TestSpec represents a test spec within a suite.
 */
export class TestSpec {
    /**
     * Creates a new TestSpec instance.
     * @param {Partial<TestSpec>} [$$source = {}] - The source object to create the TestSpec.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * passed, failed, skipped, timedOut
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestSpec(/** @type {Partial<TestSpec>} */($$parsedSource));
    }
}

/**
 * TestStats from Playwright JSON reporter.
 */
export class TestStats {
    /**
     * Creates a new TestStats instance.
     * @param {Partial<TestStats>} [$$source = {}] - The source object to create the TestStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestStats(/** @type {Partial<TestStats>} */($$parsedSource));
    }
}

/**
 * TestSuite represents a test suite in Playwright output.
 */
export class TestSuite {
    /**
     * Creates a new TestSuite instance.
     * @param {Partial<TestSuite>} [$$source = {}] - The source object to create the TestSuite.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("specs" in $$source)) {
            /**
             * @member
             * @type {TestSpec[]}
             */
            this["specs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestSuite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestSuite}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("specs" in $$parsedSource) {
            $$parsedSource["specs"] = $$createField2_0($$parsedSource["specs"]);
        }
        return new TestSuite(/** @type {Partial<TestSuite>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TestSuite.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TestStats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = TestSpec.createFrom;
const $$createType5 = $Create.Array($$createType4);
