// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages Playwright script execution.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetScripts returns all saved scripts.
 * @returns {$CancellablePromise<$models.Script[]>}
 */
export function GetScripts() {
    return $Call.ByID(3546143781).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * InstallPlaywright installs Playwright via npm.
 * @returns {$CancellablePromise<string[]>}
 */
export function InstallPlaywright() {
    return $Call.ByID(3136256895).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsPlaywrightReady returns whether Playwright is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPlaywrightReady() {
    return $Call.ByID(1792359897);
}

/**
 * RunScript executes a Playwright script and streams output via events.
 * @param {string} scriptID
 * @returns {$CancellablePromise<void>}
 */
export function RunScript(scriptID) {
    return $Call.ByID(561900957, scriptID);
}

/**
 * RunTest runs a Playwright test file and returns structured results.
 * @param {string} testPath
 * @returns {$CancellablePromise<$models.TestRunResult | null>}
 */
export function RunTest(testPath) {
    return $Call.ByID(1942816182, testPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SaveScript saves a script to the store.
 * @param {$models.Script} script
 * @returns {$CancellablePromise<void>}
 */
export function SaveScript(script) {
    return $Call.ByID(2308443535, script);
}

/**
 * SetApp sets the Wails app reference for event emission.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3793630754, app);
}

/**
 * StopScript kills the running Playwright process for a script.
 * @param {string} scriptID
 * @returns {$CancellablePromise<void>}
 */
export function StopScript(scriptID) {
    return $Call.ByID(63223854, scriptID);
}

// Private type creation functions
const $$createType0 = $models.Script.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.TestRunResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
