// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionConfig holds parameters for a remote connection.
 */
export class ConnectionConfig {
    /**
     * Creates a new ConnectionConfig instance.
     * @param {Partial<ConnectionConfig>} [$$source = {}] - The source object to create the ConnectionConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ConnectionType}
             */
            this["type"] = ConnectionType.$zero;
        }
        if (!("host" in $$source)) {
            /**
             * SSH fields
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Docker fields
             * @member
             * @type {string | undefined}
             */
            this["containerId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["containerName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig(/** @type {Partial<ConnectionConfig>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus reports the live state of a connection.
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * ConnectionType identifies the remote connection kind.
 * @readonly
 * @enum {string}
 */
export const ConnectionType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TypeSSH: "ssh",
    TypeDocker: "docker",
};

/**
 * DockerContainer describes a running container.
 */
export class DockerContainer {
    /**
     * Creates a new DockerContainer instance.
     * @param {Partial<DockerContainer>} [$$source = {}] - The source object to create the DockerContainer.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerContainer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DockerContainer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerContainer(/** @type {Partial<DockerContainer>} */($$parsedSource));
    }
}

/**
 * RemoteFile mirrors filesystem.FileNode for remote paths.
 */
export class RemoteFile {
    /**
     * Creates a new RemoteFile instance.
     * @param {Partial<RemoteFile>} [$$source = {}] - The source object to create the RemoteFile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RemoteFile[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteFile}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new RemoteFile(/** @type {Partial<RemoteFile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RemoteFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
