// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages remote connections and exposes them to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConnection saves a new connection config.
 * @param {$models.ConnectionConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function AddConnection(cfg) {
    return $Call.ByID(815936133, cfg);
}

/**
 * Connect establishes an SSH connection.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Connect(id) {
    return $Call.ByID(1616327248, id);
}

/**
 * Disconnect closes an active connection.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(id) {
    return $Call.ByID(3610189108, id);
}

/**
 * DockerExec runs a command inside a container and returns stdout.
 * @param {string} containerID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function DockerExec(containerID, command) {
    return $Call.ByID(1284665971, containerID, command);
}

/**
 * DockerListDir lists a directory inside a container.
 * @param {string} containerID
 * @param {string} path
 * @returns {$CancellablePromise<$models.RemoteFile[]>}
 */
export function DockerListDir(containerID, path) {
    return $Call.ByID(116244985, containerID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DockerReadFile reads a file from a container.
 * @param {string} containerID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function DockerReadFile(containerID, path) {
    return $Call.ByID(3558182008, containerID, path);
}

/**
 * DockerWriteFile writes content to a file inside a container.
 * @param {string} containerID
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function DockerWriteFile(containerID, path, content) {
    return $Call.ByID(2714595111, containerID, path, content);
}

/**
 * GetConnectionStatus returns live status for all configs.
 * @returns {$CancellablePromise<$models.ConnectionStatus[]>}
 */
export function GetConnectionStatus() {
    return $Call.ByID(346832932).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetConnections returns all saved connection configs.
 * @returns {$CancellablePromise<$models.ConnectionConfig[]>}
 */
export function GetConnections() {
    return $Call.ByID(2216294283).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListDockerContainers returns running Docker containers on the local machine.
 * @returns {$CancellablePromise<$models.DockerContainer[]>}
 */
export function ListDockerContainers() {
    return $Call.ByID(766258462).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * RemoteExec runs a command on the remote host and returns stdout.
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RemoteExec(connID, command) {
    return $Call.ByID(2179764177, connID, command);
}

/**
 * RemoteListDir lists a directory on the remote host.
 * @param {string} connID
 * @param {string} path
 * @returns {$CancellablePromise<$models.RemoteFile[]>}
 */
export function RemoteListDir(connID, path) {
    return $Call.ByID(230272167, connID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RemoteReadFile reads a file on the remote host.
 * @param {string} connID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function RemoteReadFile(connID, path) {
    return $Call.ByID(2014683050, connID, path);
}

/**
 * RemoteWriteFile writes content to a file on the remote host.
 * @param {string} connID
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function RemoteWriteFile(connID, path, content) {
    return $Call.ByID(1310800329, connID, path, content);
}

/**
 * RemoveConnection removes a saved config and disconnects if active.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnection(id) {
    return $Call.ByID(935295122, id);
}

/**
 * StartRemoteTerminalPort starts a WebSocket server that proxies a remote SSH shell.
 * Returns the local port.
 * @param {string} connID
 * @returns {$CancellablePromise<number>}
 */
export function StartRemoteTerminalPort(connID) {
    return $Call.ByID(1869433203, connID);
}

// Private type creation functions
const $$createType0 = $models.RemoteFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ConnectionStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ConnectionConfig.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.DockerContainer.createFrom;
const $$createType7 = $Create.Array($$createType6);
