// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Message represents a single message in the conversation.
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {MessageRole}
             */
            this["role"] = MessageRole.$zero;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uuid"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * ToolUseID is set when this message is a tool result.
             * @member
             * @type {string | undefined}
             */
            this["toolUseId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ToolName is set when the assistant is invoking a tool.
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ToolArgs is set when the assistant is invoking a tool.
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["toolArgs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * IsCompactSummary marks this as a compaction summary.
             * @member
             * @type {boolean | undefined}
             */
            this["isCompactSummary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Success indicates tool execution success.
             * @member
             * @type {boolean | undefined}
             */
            this["success"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolArgs" in $$parsedSource) {
            $$parsedSource["toolArgs"] = $$createField6_0($$parsedSource["toolArgs"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * MessageRole represents the role of a message sender.
 * @readonly
 * @enum {string}
 */
export const MessageRole = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RoleUser: "user",
    RoleAssistant: "assistant",
    RoleSystem: "system",
    RoleTool: "tool",
};

/**
 * RalphLoopResult holds the result of a Ralph Loop execution.
 */
export class RalphLoopResult {
    /**
     * Creates a new RalphLoopResult instance.
     * @param {Partial<RalphLoopResult>} [$$source = {}] - The source object to create the RalphLoopResult.
     */
    constructor($$source = {}) {
        if (!("verdict" in $$source)) {
            /**
             * @member
             * @type {RalphVerdict}
             */
            this["verdict"] = RalphVerdict.$zero;
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("fixesApplied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fixesApplied"] = 0;
        }
        if (!("report" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["report"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {Message[]}
             */
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RalphLoopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RalphLoopResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        return new RalphLoopResult(/** @type {Partial<RalphLoopResult>} */($$parsedSource));
    }
}

/**
 * RalphVerdict is the outcome of a Ralph Loop.
 * @readonly
 * @enum {string}
 */
export const RalphVerdict = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    VerdictPass: "PASS",
    VerdictFail: "FAIL",
    VerdictPartial: "PARTIAL",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Message.createFrom;
const $$createType2 = $Create.Array($$createType1);
