// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages LSP server processes and exposes a WebSocket bridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckLspInstalled returns true if the LSP binary for the given language is found.
 * Searches user binDir, per-lang overrides, and extended PATH.
 * @param {string} lang
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckLspInstalled(lang) {
    return $Call.ByID(2193560874, lang);
}

/**
 * GetLspBinDir returns the effective LSP binary directory shown in settings UI.
 * @returns {$CancellablePromise<string>}
 */
export function GetLspBinDir() {
    return $Call.ByID(2107629848);
}

/**
 * InstallLsp installs the LSP server for the given language into s.binDir.
 * Streams log lines to the returned channel; last line is "OK" or "ERROR: <msg>".
 * @param {string} lang
 * @returns {$CancellablePromise<any>}
 */
export function InstallLsp(lang) {
    return $Call.ByID(1441943761, lang);
}

/**
 * InstallLspStream is the Wails-callable wrapper: runs InstallLsp and returns all output lines at once.
 * For real-time streaming, use the WebSocket approach via InstallLspWS.
 * @param {string} lang
 * @returns {$CancellablePromise<string[]>}
 */
export function InstallLspStream(lang) {
    return $Call.ByID(2245533033, lang).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LookupCommand returns the LSP command for a given language or extension ID.
 * If the user has configured a per-language binary path, it is substituted as cmd[0].
 * @param {string} langOrExtID
 * @returns {$CancellablePromise<string[]>}
 */
export function LookupCommand(langOrExtID) {
    return $Call.ByID(1266332842, langOrExtID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetBinDir updates the LSP binary directory and per-language overrides.
 * Called by main after config loads and on every settings save.
 * @param {string} binDir
 * @param {{ [_ in string]?: string }} langPaths
 * @returns {$CancellablePromise<void>}
 */
export function SetBinDir(binDir, langPaths) {
    return $Call.ByID(1478717265, binDir, langPaths);
}

/**
 * StartAndGetPort starts the WebSocket LSP bridge server (idempotent) and returns the port.
 * @returns {$CancellablePromise<number>}
 */
export function StartAndGetPort() {
    return $Call.ByID(4191008113);
}

/**
 * StopAll terminates all running LSP processes (call on app shutdown).
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(1268644574);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
