// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdapterType identifies which DAP debug adapter to use.
 * @readonly
 * @enum {string}
 */
export const AdapterType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Go via Delve
     */
    AdapterDlv: "dlv",

    /**
     * C/C++/Obj-C/Rust/Swift via LLDB DAP
     */
    AdapterLldbDap: "lldb-dap",

    /**
     * Python via debugpy
     */
    AdapterDebugpy: "debugpy",

    /**
     * Node.js/JavaScript via js-debug-dap
     */
    AdapterJsDebug: "js-debug",

    /**
     * Java via java-debug
     */
    AdapterJavaDebug: "java-debug",

    /**
     * Dart/Flutter via SDK DAP
     */
    AdapterDart: "dart",
};

/**
 * DebugStatus describes the current debug state for a project.
 */
export class DebugStatus {
    /**
     * Creates a new DebugStatus instance.
     * @param {Partial<DebugStatus>} [$$source = {}] - The source object to create the DebugStatus.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * "dlv", "lldb-dap", or "" if not active
             * @member
             * @type {AdapterType | undefined}
             */
            this["adapter"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["language"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DebugStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DebugStatus(/** @type {Partial<DebugStatus>} */($$parsedSource));
    }
}
