// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages debug sessions via DAP adapters + WebSocket proxy.
 * Supported adapters: dlv (Go), lldb-dap (C/C++/Rust).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanLegacyDebugBins scans all known project roots for legacy __debug_bin*
 * files left behind by older versions that wrote directly into the project dir.
 * Call once on startup.
 * @returns {$CancellablePromise<void>}
 */
export function CleanLegacyDebugBins() {
    return $Call.ByID(3394996636);
}

/**
 * DetectAdapterType inspects the project root and returns the best DAP adapter.
 * Returns ("", nil) for languages without a DAP adapter (run-fallback).
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.AdapterType>}
 */
export function DetectAdapterType(rootPath) {
    return $Call.ByID(1066949487, rootPath);
}

/**
 * GetDebugStatus returns the current debug status for a project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.DebugStatus>}
 */
export function GetDebugStatus(rootPath) {
    return $Call.ByID(1862580278, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * InstallDlv ensures dlv is available, downloading it if necessary.
 * @returns {$CancellablePromise<string>}
 */
export function InstallDlv() {
    return $Call.ByID(2819310752);
}

/**
 * IsDartInstalled reports whether the Dart SDK is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDartInstalled() {
    return $Call.ByID(355850040);
}

/**
 * IsDebugging reports whether a debug session is active for the project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDebugging(rootPath) {
    return $Call.ByID(3494343033, rootPath);
}

/**
 * IsDebugpyInstalled reports whether debugpy is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDebugpyInstalled() {
    return $Call.ByID(2923149065);
}

/**
 * IsDlvInstalled reports whether dlv is available (managed cache, ~/go/bin, or PATH).
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDlvInstalled() {
    return $Call.ByID(3086984567);
}

/**
 * IsJavaDebugInstalled reports whether java-debug is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsJavaDebugInstalled() {
    return $Call.ByID(317093168);
}

/**
 * IsJsDebugInstalled reports whether js-debug-dap is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsJsDebugInstalled() {
    return $Call.ByID(234237535);
}

/**
 * IsLldbDapInstalled reports whether lldb-dap is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLldbDapInstalled() {
    return $Call.ByID(130094176);
}

/**
 * ScanMainPackages walks rootPath and returns relative paths (from rootPath) of
 * every directory that contains at least one file declaring "package main".
 * Returns an error if the project is a Wails app (requires frontend to debug).
 * @param {string} rootPath
 * @returns {$CancellablePromise<string[]>}
 */
export function ScanMainPackages(rootPath) {
    return $Call.ByID(3092701866, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StartAndGetPort starts the WebSocket proxy server (idempotent) and returns its port.
 * @returns {$CancellablePromise<number>}
 */
export function StartAndGetPort() {
    return $Call.ByID(1366435621);
}

/**
 * StartDartDebug launches the Dart DAP adapter for the given project root.
 * For Flutter projects, it uses "flutter debug_adapter"; for pure Dart, "dart debug_adapter".
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartDartDebug(rootPath) {
    return $Call.ByID(3541201095, rootPath);
}

/**
 * StartDebug launches the appropriate DAP adapter for the project and returns the adapter port.
 * For projects without a DAP adapter, returns (0, nil) — the frontend should use run-fallback.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartDebug(rootPath) {
    return $Call.ByID(2933900928, rootPath);
}

/**
 * StartDebugpyDebug launches debugpy DAP adapter for the given project root.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartDebugpyDebug(rootPath) {
    return $Call.ByID(2551062786, rootPath);
}

/**
 * StartGoDebug launches dlv dap for the given project root and returns the dlv port.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartGoDebug(rootPath) {
    return $Call.ByID(4227604954, rootPath);
}

/**
 * StartJavaDebug launches java-debug DAP adapter for the given project root.
 * Java debug requires a running JDT Language Server; we launch the debug adapter
 * as a standalone process that communicates via DAP.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartJavaDebug(rootPath) {
    return $Call.ByID(646756592, rootPath);
}

/**
 * StartJsDebug launches js-debug-dap for the given project root.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartJsDebug(rootPath) {
    return $Call.ByID(1371691605, rootPath);
}

/**
 * StartLldbDapDebug launches lldb-dap for the given project root and returns the adapter port.
 * @param {string} rootPath
 * @returns {$CancellablePromise<number>}
 */
export function StartLldbDapDebug(rootPath) {
    return $Call.ByID(2644304331, rootPath);
}

/**
 * StopDebug kills the debug session for the given project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<void>}
 */
export function StopDebug(rootPath) {
    return $Call.ByID(2135240302, rootPath);
}

// Private type creation functions
const $$createType0 = $models.DebugStatus.createFrom;
const $$createType1 = $Create.Array($Create.Any);
