// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RunConfig describes a detected or user-defined launch configuration.
 */
export class RunConfig {
    /**
     * Creates a new RunConfig instance.
     * @param {Partial<RunConfig>} [$$source = {}] - The source object to create the RunConfig.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cmd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunConfig(/** @type {Partial<RunConfig>} */($$parsedSource));
    }
}

/**
 * RunEnvConfig holds per-project runtime environment settings.
 */
export class RunEnvConfig {
    /**
     * Creates a new RunEnvConfig instance.
     * @param {Partial<RunEnvConfig>} [$$source = {}] - The source object to create the RunEnvConfig.
     */
    constructor($$source = {}) {
        if (!("preCmd" in $$source)) {
            /**
             * shell command to run before the main cmd
             * @member
             * @type {string}
             */
            this["preCmd"] = "";
        }
        if (!("env" in $$source)) {
            /**
             * extra environment variables
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env"] = {};
        }
        if (!("buildFlags" in $$source)) {
            /**
             * extra flags passed to go build / dlv launch
             * @member
             * @type {string}
             */
            this["buildFlags"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEnvConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunEnvConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField1_0($$parsedSource["env"]);
        }
        return new RunEnvConfig(/** @type {Partial<RunEnvConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
