// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages running project processes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectRunCommand returns the detected start command string for display.
 * @param {string} rootPath
 * @returns {$CancellablePromise<string>}
 */
export function DetectRunCommand(rootPath) {
    return $Call.ByID(3030010836, rootPath);
}

/**
 * DetectRunEnv inspects the project and returns suggested runtime environment.
 * If a vendor directory exists, it suggests a pre-run command to fix it.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.RunEnvConfig>}
 */
export function DetectRunEnv(rootPath) {
    return $Call.ByID(2438865866, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetProcessOutput returns the last N lines of stdout+stderr for the project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetProcessOutput(rootPath) {
    return $Call.ByID(4210464397, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRunEnvConfig returns the stored runtime env config for a project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.RunEnvConfig>}
 */
export function GetRunEnvConfig(rootPath) {
    return $Call.ByID(2907680569, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * IsRunning returns whether the project's process is currently active.
 * @param {string} rootPath
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning(rootPath) {
    return $Call.ByID(3335079552, rootPath);
}

/**
 * ScanRunConfigs returns all detected launch configurations for the project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.RunConfig[]>}
 */
export function ScanRunConfigs(rootPath) {
    return $Call.ByID(3938537168, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetRunEnvConfig stores the runtime env config for a project.
 * @param {string} rootPath
 * @param {$models.RunEnvConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetRunEnvConfig(rootPath, cfg) {
    return $Call.ByID(3420749253, rootPath, cfg);
}

/**
 * StartProject detects the project type and starts the default run command.
 * @param {string} rootPath
 * @returns {$CancellablePromise<void>}
 */
export function StartProject(rootPath) {
    return $Call.ByID(263047544, rootPath);
}

/**
 * StartProjectWithCmd starts the project using a user-specified command string.
 * It respects the stored RunEnvConfig: runs PreCmd first, then injects extra Env vars.
 * @param {string} rootPath
 * @param {string} cmdStr
 * @returns {$CancellablePromise<void>}
 */
export function StartProjectWithCmd(rootPath, cmdStr) {
    return $Call.ByID(410999928, rootPath, cmdStr);
}

/**
 * StopProject kills the running process for the given project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<void>}
 */
export function StopProject(rootPath) {
    return $Call.ByID(4058692594, rootPath);
}

// Private type creation functions
const $$createType0 = $models.RunEnvConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.RunConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
