// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIProviderConfig stores credentials for a remote API provider.
 */
export class APIProviderConfig {
    /**
     * Creates a new APIProviderConfig instance.
     * @param {Partial<APIProviderConfig>} [$$source = {}] - The source object to create the APIProviderConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIProviderConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIProviderConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIProviderConfig(/** @type {Partial<APIProviderConfig>} */($$parsedSource));
    }
}

/**
 * AgentRunResult contains the result of an agent run.
 */
export class AgentRunResult {
    /**
     * Creates a new AgentRunResult instance.
     * @param {Partial<AgentRunResult>} [$$source = {}] - The source object to create the AgentRunResult.
     */
    constructor($$source = {}) {
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {ChatMessage[]}
             */
            this["messages"] = [];
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new AgentRunResult(/** @type {Partial<AgentRunResult>} */($$parsedSource));
    }
}

/**
 * ChatMessage is a single message in the conversation.
 */
export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * tool name for tool_call/tool_result
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

/**
 * ModelInfo describes a model loaded in LM Studio.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("object" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["object"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * WebProviderInfo is a simplified provider info for the frontend.
 */
export class WebProviderInfo {
    /**
     * Creates a new WebProviderInfo instance.
     * @param {Partial<WebProviderInfo>} [$$source = {}] - The source object to create the WebProviderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("loginUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loginUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebProviderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebProviderInfo(/** @type {Partial<WebProviderInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
