// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages LM Studio integration and AI chat/agent capabilities.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../skills/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentRun executes the TAOR (Think-Act-Observe-Repeat) loop.
 * It sends the user's message, lets the model think and use tools,
 * and iterates until the model produces a final text response or
 * reaches maxIterations.
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @returns {$CancellablePromise<$models.AgentRunResult>}
 */
export function AgentRun(userMessage, rootPath, maxIterations) {
    return $Call.ByID(1497785036, userMessage, rootPath, maxIterations).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AgentRunAPI executes the TAOR loop using a remote API provider.
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @returns {$CancellablePromise<$models.AgentRunResult>}
 */
export function AgentRunAPI(userMessage, rootPath, maxIterations) {
    return $Call.ByID(4117683140, userMessage, rootPath, maxIterations).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AgentRunAdvanced executes the agent loop using the full agent subsystem
 * (config, memory, compact, safety, roles, parallel, tools, mcp, ralph).
 * It accepts a mode string ("local", "api", "web") to select the chat backend.
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @param {string} mode
 * @returns {$CancellablePromise<agent$0.AgentRunResult>}
 */
export function AgentRunAdvanced(userMessage, rootPath, maxIterations, mode) {
    return $Call.ByID(3289565126, userMessage, rootPath, maxIterations, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AgentRunWeb executes the agent loop using a web AI provider.
 * Follows the same pattern as Python's agent_loop.agent_chat:
 * 1. Inject tool descriptions into the first user message
 * 2. Parse tool calls from the response
 * 3. Execute tools and send <tool_result> blocks as the next message
 * 4. Repeat until no tool calls or max iterations reached
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @returns {$CancellablePromise<$models.AgentRunResult>}
 */
export function AgentRunWeb(userMessage, rootPath, maxIterations) {
    return $Call.ByID(3569878794, userMessage, rootPath, maxIterations).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AgentStream runs the TAOR loop and streams events via a channel.
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @returns {$CancellablePromise<any>}
 */
export function AgentStream(userMessage, rootPath, maxIterations) {
    return $Call.ByID(2065636739, userMessage, rootPath, maxIterations);
}

/**
 * Chat sends a non-streaming chat request and returns the full response.
 * @param {$models.ChatMessage[]} messages
 * @returns {$CancellablePromise<string>}
 */
export function Chat(messages) {
    return $Call.ByID(1039614400, messages);
}

/**
 * ChatAPI sends a non-streaming chat request to a remote API provider.
 * It uses the provider's base URL, API key, and model.
 * @param {$models.ChatMessage[]} messages
 * @returns {$CancellablePromise<string>}
 */
export function ChatAPI(messages) {
    return $Call.ByID(4187612304, messages);
}

/**
 * ChatStream sends a streaming chat request. It calls onToken for each token
 * received and returns the full accumulated response.
 * @param {$models.ChatMessage[]} messages
 * @param {any} onToken
 * @returns {$CancellablePromise<string>}
 */
export function ChatStream(messages, onToken) {
    return $Call.ByID(2691985536, messages, onToken);
}

/**
 * ChatWeb sends a chat message to the active web provider.
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function ChatWeb(message) {
    return $Call.ByID(775496022, message);
}

/**
 * ConnectMCPServer connects to an MCP server via the agent subsystem.
 * @param {string} name
 * @param {string} serverType
 * @param {string} command
 * @param {string[]} args
 * @param {{ [_ in string]?: string }} env
 * @returns {$CancellablePromise<void>}
 */
export function ConnectMCPServer(name, serverType, command, args, env) {
    return $Call.ByID(2205862251, name, serverType, command, args, env);
}

/**
 * GetAPIProvider returns the current API provider config.
 * @returns {$CancellablePromise<$models.APIProviderConfig>}
 */
export function GetAPIProvider() {
    return $Call.ByID(2235958635).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAPIURL returns the current API URL.
 * @returns {$CancellablePromise<string>}
 */
export function GetAPIURL() {
    return $Call.ByID(3537642047);
}

/**
 * GetAgentConfigFiles returns loaded TIANCAN.md config files for a project.
 * @param {string} rootPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAgentConfigFiles(rootPath) {
    return $Call.ByID(1721554952, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetWebAuth returns the current web provider ID (or empty if not set).
 * Auto-loads persisted auth from disk if not already in memory.
 * @returns {$CancellablePromise<string>}
 */
export function GetWebAuth() {
    return $Call.ByID(2261624570);
}

/**
 * InstallLMStudio downloads and installs LM Studio.
 * Returns log lines as the installation progresses.
 * @returns {$CancellablePromise<string[]>}
 */
export function InstallLMStudio() {
    return $Call.ByID(3066472064).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsLMStudioInstalled reports whether LM Studio is available (running or installed).
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLMStudioInstalled() {
    return $Call.ByID(1041437491);
}

/**
 * IsWebProviderLoggedIn checks if a specific web provider has valid auth.
 * Checks in-memory state first, then falls back to disk-persisted tokens.
 * @param {string} providerID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWebProviderLoggedIn(providerID) {
    return $Call.ByID(161614372, providerID);
}

/**
 * LaunchLMStudio starts the LM Studio application.
 * @returns {$CancellablePromise<void>}
 */
export function LaunchLMStudio() {
    return $Call.ByID(1528937972);
}

/**
 * ListAPIProviders returns the built-in list of known API providers.
 * @returns {$CancellablePromise<$models.APIProviderConfig[]>}
 */
export function ListAPIProviders() {
    return $Call.ByID(3677865512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListModels returns the list of loaded models in LM Studio.
 * @returns {$CancellablePromise<$models.ModelInfo[]>}
 */
export function ListModels() {
    return $Call.ByID(1247300092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListSkills returns available skills for the current project.
 * @returns {$CancellablePromise<skills$0.SkillInfo[]>}
 */
export function ListSkills() {
    return $Call.ByID(3926112952).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListWebProviders returns the list of available web AI providers.
 * @returns {$CancellablePromise<$models.WebProviderInfo[]>}
 */
export function ListWebProviders() {
    return $Call.ByID(490617310).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * LoginWeb launches a Playwright browser for the user to authenticate.
 * It runs the login flow in a goroutine and emits events:
 *   - webai:login-success → {provider, cookie, bearer, ...}
 *   - webai:login-error   → {error: "..."}
 *   - webai:login-fallback → opens default browser as fallback
 * @param {string} providerID
 * @returns {$CancellablePromise<void>}
 */
export function LoginWeb(providerID) {
    return $Call.ByID(1261781843, providerID);
}

/**
 * RespondPermission allows the frontend to approve or deny a pending permission request.
 * @param {string} requestID
 * @param {boolean} approved
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(requestID, approved) {
    return $Call.ByID(2179028216, requestID, approved);
}

/**
 * SetAPIProvider sets the active remote API provider (name, base URL, key, model).
 * @param {string} name
 * @param {string} baseURL
 * @param {string} apiKey
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIProvider(name, baseURL, apiKey, model) {
    return $Call.ByID(65998159, name, baseURL, apiKey, model);
}

/**
 * SetAPIURL sets the LM Studio API base URL.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIURL(url) {
    return $Call.ByID(1931463579, url);
}

/**
 * SetModel sets the active model for chat.
 * @param {string} modelID
 * @returns {$CancellablePromise<void>}
 */
export function SetModel(modelID) {
    return $Call.ByID(1302901587, modelID);
}

/**
 * SetWebAuth saves the user-provided auth credentials for a web provider.
 * The user copies cookies from the browser after login.
 * @param {string} providerID
 * @param {string} cookie
 * @param {string} userAgent
 * @returns {$CancellablePromise<void>}
 */
export function SetWebAuth(providerID, cookie, userAgent) {
    return $Call.ByID(583541470, providerID, cookie, userAgent);
}

/**
 * StartAgentStream starts the streaming agent loop and pushes events to the
 * frontend via Wails Events. The frontend should listen on the "agent:stream" event.
 * This method returns immediately; events are delivered asynchronously.
 * @param {string} userMessage
 * @param {string} rootPath
 * @param {number} maxIterations
 * @returns {$CancellablePromise<void>}
 */
export function StartAgentStream(userMessage, rootPath, maxIterations) {
    return $Call.ByID(2956710931, userMessage, rootPath, maxIterations);
}

// Private type creation functions
const $$createType0 = $models.AgentRunResult.createFrom;
const $$createType1 = agent$0.AgentRunResult.createFrom;
const $$createType2 = $models.APIProviderConfig.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = $models.ModelInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = skills$0.SkillInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.WebProviderInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
