package tools

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	agenttypes "github.com/rocky233/tiancan-ai-ide/backend/agent/types"
)

// GenerateTestsTool generates unit tests for a given source file.
type GenerateTestsTool struct {
	rootPath string
}

func (t *GenerateTestsTool) Name() string { return "generate_tests" }
func (t *GenerateTestsTool) Description() string {
	return "Generate unit tests for a source file. Reads the file, creates a test file, and runs the tests. Supports Go, Python, JavaScript/TypeScript."
}
func (t *GenerateTestsTool) InputSchema() map[string]interface{} {
	return map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"file_path": map[string]interface{}{
				"type":        "string",
				"description": "Path to the source file to generate tests for",
			},
			"test_content": map[string]interface{}{
				"type":        "string",
				"description": "The test code to write (generated by AI). For Go: test functions. For Python: test functions. For JS/TS: describe/it blocks.",
			},
			"run": map[string]interface{}{
				"type":        "boolean",
				"description": "Whether to run the tests after writing (default: true)",
			},
		},
		"required": []string{"file_path", "test_content"},
	}
}
func (t *GenerateTestsTool) IsReadOnly() bool        { return false }
func (t *GenerateTestsTool) IsConcurrencySafe() bool { return false }
func (t *GenerateTestsTool) Execute(ctx context.Context, args map[string]interface{}) (agenttypes.ToolResult, error) {
	filePath, _ := args["file_path"].(string)
	testContent, _ := args["test_content"].(string)
	shouldRun := true
	if v, ok := args["run"].(bool); ok {
		shouldRun = v
	}

	if filePath == "" || testContent == "" {
		return agenttypes.ToolResult{Success: false, Error: "file_path and test_content are required"}, nil
	}

	// Resolve to absolute path
	absPath := filePath
	if !filepath.IsAbs(filePath) {
		absPath = filepath.Join(t.rootPath, filePath)
	}

	// Determine test file path based on language
	testPath := deriveTestFilePath(absPath)
	if testPath == "" {
		return agenttypes.ToolResult{Success: false, Error: "unsupported file type for test generation"}, nil
	}

	// Write test file
	if err := os.MkdirAll(filepath.Dir(testPath), 0o755); err != nil {
		return agenttypes.ToolResult{Success: false, Error: fmt.Sprintf("create test dir: %v", err)}, nil
	}
	if err := os.WriteFile(testPath, []byte(testContent), 0o644); err != nil {
		return agenttypes.ToolResult{Success: false, Error: fmt.Sprintf("write test file: %v", err)}, nil
	}

	var report strings.Builder
	report.WriteString(fmt.Sprintf("Test file written: %s\n", testPath))

	// Run tests if requested
	if shouldRun {
		result := t.runTests(ctx, absPath, testPath)
		report.WriteString(fmt.Sprintf("Test execution:\n%s\n", result))
	}

	return agenttypes.ToolResult{Success: true, Content: report.String()}, nil
}

// deriveTestFilePath returns the conventional test file path for a given source file.
func deriveTestFilePath(srcPath string) string {
	ext := filepath.Ext(srcPath)
	base := strings.TrimSuffix(filepath.Base(srcPath), ext)
	dir := filepath.Dir(srcPath)

	switch ext {
	case ".go":
		// foo.go -> foo_test.go
		return filepath.Join(dir, base+"_test.go")
	case ".py":
		// foo.py -> test_foo.py
		return filepath.Join(dir, "test_"+base+".py")
	case ".js", ".jsx", ".ts", ".tsx":
		// foo.ts -> foo.test.ts
		return filepath.Join(dir, base+".test"+ext)
	default:
		return ""
	}
}

// runTests runs the appropriate test command for the file type.
func (t *GenerateTestsTool) runTests(ctx context.Context, srcPath, testPath string) string {
	ext := filepath.Ext(srcPath)
	dir := filepath.Dir(testPath)

	switch ext {
	case ".go":
		// Go: go test ./<package> -v
		pkgDir := dir
		if rel, err := filepath.Rel(t.rootPath, dir); err == nil && rel != "." {
			pkgDir = "./" + rel
		} else {
			pkgDir = "."
		}
		cmd := exec.CommandContext(ctx, "go", "test", pkgDir, "-v", "-count=1")
		cmd.Dir = t.rootPath
		out, err := cmd.CombinedOutput()
		result := string(out)
		if err != nil {
			result += fmt.Sprintf("\nError: %v", err)
		}
		return result

	case ".py":
		// Python: pytest <test_file> -v
		cmd := exec.CommandContext(ctx, "python", "-m", "pytest", testPath, "-v")
		cmd.Dir = dir
		out, err := cmd.CombinedOutput()
		result := string(out)
		if err != nil {
			result += fmt.Sprintf("\nError: %v", err)
		}
		return result

	case ".js", ".jsx", ".ts", ".tsx":
		// Node: npx jest <test_file> or npm test
		cmd := exec.CommandContext(ctx, "npx", "jest", testPath, "--no-coverage")
		cmd.Dir = t.rootPath
		out, err := cmd.CombinedOutput()
		result := string(out)
		if err != nil {
			result += fmt.Sprintf("\nError: %v", err)
		}
		return result

	default:
		return "No test runner available for this file type"
	}
}

// AssessCompletionTool evaluates how well a task was completed.
type AssessCompletionTool struct {
	rootPath string
}

func (t *AssessCompletionTool) Name() string { return "assess_completion" }
func (t *AssessCompletionTool) Description() string {
	return "Assess task completion by checking build status, test results, and code quality. Returns a structured completion score."
}
func (t *AssessCompletionTool) InputSchema() map[string]interface{} {
	return map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"task_description": map[string]interface{}{
				"type":        "string",
				"description": "The original task description to assess against",
			},
			"files_changed": map[string]interface{}{
				"type":        "array",
				"description": "List of files that were changed",
				"items":       map[string]interface{}{"type": "string"},
			},
			"check_build": map[string]interface{}{
				"type":        "boolean",
				"description": "Whether to check if the project builds (default: true)",
			},
			"check_tests": map[string]interface{}{
				"type":        "boolean",
				"description": "Whether to run the test suite (default: true)",
			},
			"check_lint": map[string]interface{}{
				"type":        "boolean",
				"description": "Whether to run the linter (default: false)",
			},
		},
		"required": []string{"task_description"},
	}
}
func (t *AssessCompletionTool) IsReadOnly() bool        { return true }
func (t *AssessCompletionTool) IsConcurrencySafe() bool { return true }
func (t *AssessCompletionTool) Execute(ctx context.Context, args map[string]interface{}) (agenttypes.ToolResult, error) {
	taskDesc, _ := args["task_description"].(string)
	if taskDesc == "" {
		return agenttypes.ToolResult{Success: false, Error: "task_description is required"}, nil
	}

	checkBuild := true
	checkTests := true
	checkLint := false
	if v, ok := args["check_build"].(bool); ok {
		checkBuild = v
	}
	if v, ok := args["check_tests"].(bool); ok {
		checkTests = v
	}
	if v, ok := args["check_lint"].(bool); ok {
		checkLint = v
	}

	var report strings.Builder
	score := 0
	maxScore := 0

	// Check 1: Build
	if checkBuild {
		maxScore += 30
		buildOK := t.checkBuild(ctx)
		if buildOK {
			score += 30
			report.WriteString("✅ Build: PASS\n")
		} else {
			report.WriteString("❌ Build: FAIL\n")
		}
	}

	// Check 2: Tests
	if checkTests {
		maxScore += 30
		testResult := t.runTestSuite(ctx)
		if testResult.passed {
			score += 30
			report.WriteString(fmt.Sprintf("✅ Tests: PASS (%d/%d passed)\n", testResult.passedCount, testResult.totalCount))
		} else if testResult.totalCount > 0 {
			partialScore := (testResult.passedCount * 30) / testResult.totalCount
			score += partialScore
			report.WriteString(fmt.Sprintf("🔶 Tests: PARTIAL (%d/%d passed)\n", testResult.passedCount, testResult.totalCount))
		} else {
			report.WriteString("❌ Tests: FAIL (no tests found or run failed)\n")
		}
	}

	// Check 3: Lint
	if checkLint {
		maxScore += 20
		lintOK := t.checkLint(ctx)
		if lintOK {
			score += 20
			report.WriteString("✅ Lint: PASS\n")
		} else {
			report.WriteString("❌ Lint: FAIL\n")
		}
	}

	// Check 4: Files changed relevance
	maxScore += 20
	filesChanged, _ := args["files_changed"].([]interface{})
	if len(filesChanged) > 0 {
		score += 20
		report.WriteString(fmt.Sprintf("✅ Files changed: %d files modified\n", len(filesChanged)))
	} else {
		report.WriteString("⚠️ No files changed recorded\n")
	}

	// Overall score
	percentage := 0
	if maxScore > 0 {
		percentage = (score * 100) / maxScore
	}

	report.WriteString(fmt.Sprintf("\n=== Completion Score: %d/%d (%d%%) ===\n", score, maxScore, percentage))

	verdict := "FAIL"
	if percentage >= 80 {
		verdict = "PASS"
	} else if percentage >= 50 {
		verdict = "PARTIAL"
	}
	report.WriteString(fmt.Sprintf("VERDICT: %s\n", verdict))

	return agenttypes.ToolResult{Success: percentage >= 50, Content: report.String()}, nil
}

type testSuiteResult struct {
	passed      bool
	passedCount int
	totalCount  int
}

func (t *AssessCompletionTool) checkBuild(ctx context.Context) bool {
	// Detect project type and run build
	if _, err := os.Stat(filepath.Join(t.rootPath, "go.mod")); err == nil {
		cmd := exec.CommandContext(ctx, "go", "build", "./...")
		cmd.Dir = t.rootPath
		return cmd.Run() == nil
	}
	if _, err := os.Stat(filepath.Join(t.rootPath, "package.json")); err == nil {
		cmd := exec.CommandContext(ctx, "npm", "run", "build")
		cmd.Dir = t.rootPath
		return cmd.Run() == nil
	}
	// No build system detected — assume OK
	return true
}

func (t *AssessCompletionTool) runTestSuite(ctx context.Context) testSuiteResult {
	// Detect project type and run tests
	if _, err := os.Stat(filepath.Join(t.rootPath, "go.mod")); err == nil {
		cmd := exec.CommandContext(ctx, "go", "test", "./...", "-v", "-count=1")
		cmd.Dir = t.rootPath
		out, _ := cmd.CombinedOutput()
		return parseGoTestVerbose(string(out))
	}
	if _, err := os.Stat(filepath.Join(t.rootPath, "package.json")); err == nil {
		cmd := exec.CommandContext(ctx, "npm", "test")
		cmd.Dir = t.rootPath
		out, _ := cmd.CombinedOutput()
		return parseJSTestVerbose(string(out))
	}
	return testSuiteResult{passed: true, passedCount: 0, totalCount: 0}
}

func (t *AssessCompletionTool) checkLint(ctx context.Context) bool {
	if _, err := os.Stat(filepath.Join(t.rootPath, "go.mod")); err == nil {
		cmd := exec.CommandContext(ctx, "go", "vet", "./...")
		cmd.Dir = t.rootPath
		return cmd.Run() == nil
	}
	// Assume OK if no linter configured
	return true
}

// parseGoTestVerbose parses `go test -v` output for pass/fail counts.
func parseGoTestVerbose(output string) testSuiteResult {
	passRe := regexp.MustCompile(`--- PASS:`)
	failRe := regexp.MustCompile(`--- FAIL:`)
	passed := len(passRe.FindAllString(output, -1))
	failed := len(failRe.FindAllString(output, -1))
	total := passed + failed
	return testSuiteResult{
		passed:      failed == 0 && total > 0,
		passedCount: passed,
		totalCount:  total,
	}
}

// parseJSTestVerbose parses npm test output for pass/fail counts.
func parseJSTestVerbose(output string) testSuiteResult {
	// Jest format: "Tests: X failed, Y passed, Z total"
	re := regexp.MustCompile(`(\d+) passed`)
	passMatch := re.FindStringSubmatch(output)
	passed := 0
	if len(passMatch) > 1 {
		fmt.Sscanf(passMatch[1], "%d", &passed)
	}

	failRe := regexp.MustCompile(`(\d+) failed`)
	failMatch := failRe.FindStringSubmatch(output)
	failed := 0
	if len(failMatch) > 1 {
		fmt.Sscanf(failMatch[1], "%d", &failed)
	}

	total := passed + failed
	return testSuiteResult{
		passed:      failed == 0 && total > 0,
		passedCount: passed,
		totalCount:  total,
	}
}
