// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings is the main IDE configuration structure.
 * Stored at ~/.tiancan/settings.json
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("fontSize" in $$source)) {
            /**
             * Editor
             * @member
             * @type {number}
             */
            this["fontSize"] = 0;
        }
        if (!("tabSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tabSize"] = 0;
        }
        if (!("wordWrap" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["wordWrap"] = false;
        }
        if (!("minimap" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["minimap"] = false;
        }
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("lineHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineHeight"] = 0;
        }
        if (!("renderWhitespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renderWhitespace"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * Theme
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("lmStudioUrl" in $$source)) {
            /**
             * AI
             * @member
             * @type {string}
             */
            this["lmStudioUrl"] = "";
        }
        if (!("defaultModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultModel"] = "";
        }
        if (!("inlineCompletion" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inlineCompletion"] = false;
        }
        if (!("autoCheckUpdate" in $$source)) {
            /**
             * Update
             * @member
             * @type {boolean}
             */
            this["autoCheckUpdate"] = false;
        }
        if (!("checkedVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedVersion"] = "";
        }
        if (!("lspBinDir" in $$source)) {
            /**
             * LSP
             * default ~/.tiancan/lsp-bin
             * @member
             * @type {string}
             */
            this["lspBinDir"] = "";
        }
        if (!("lspPaths" in $$source)) {
            /**
             * per-lang binary overrides, e.g. {"go": "/usr/local/bin/gopls"}
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["lspPaths"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lspPaths" in $$parsedSource) {
            $$parsedSource["lspPaths"] = $$createField14_0($$parsedSource["lspPaths"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * UpdateInfo describes an available update.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("published" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["published"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
