// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes config management and update-check to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate fetches the latest GitHub release and returns info if a newer version exists.
 * Returns nil (JSON null) if already up-to-date or check fails.
 * @returns {$CancellablePromise<$models.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(1013851712).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCurrentVersion returns the running IDE version.
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(1379499353);
}

/**
 * GetLspBinDir returns the effective LSP binary directory.
 * If the user hasn't configured one, defaults to ~/.tiancan/lsp-bin.
 * @returns {$CancellablePromise<string>}
 */
export function GetLspBinDir() {
    return $Call.ByID(777785917);
}

/**
 * GetSettings returns current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(3322873963).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSettingsPath returns the path to the settings file.
 * @returns {$CancellablePromise<string>}
 */
export function GetSettingsPath() {
    return $Call.ByID(1876960156);
}

/**
 * HasSettingsChanged returns true if the settings file changed since the last call.
 * Frontend should poll this periodically (e.g., every 2s) to detect hot-reloads.
 * @returns {$CancellablePromise<boolean>}
 */
export function HasSettingsChanged() {
    return $Call.ByID(2901487901);
}

/**
 * ResetSettings restores defaults.
 * @returns {$CancellablePromise<void>}
 */
export function ResetSettings() {
    return $Call.ByID(1652686568);
}

/**
 * SaveSettings persists settings to disk.
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(347469778, settings);
}

/**
 * StartWatcher begins polling the settings file for changes.
 * Call this once on startup. The frontend can call PollChange to detect updates.
 * @returns {$CancellablePromise<void>}
 */
export function StartWatcher() {
    return $Call.ByID(391663498);
}

/**
 * StopWatcher stops the file watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StopWatcher() {
    return $Call.ByID(1614228458);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Settings.createFrom;
