// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Extension represents a VS Code extension
 */
export class Extension {
    /**
     * Creates a new Extension instance.
     * @param {Partial<Extension>} [$$source = {}] - The source object to create the Extension.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * display name
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("technicalName" in $$source)) {
            /**
             * technical name used in API paths
             * @member
             * @type {string}
             */
            this["technicalName"] = "";
        }
        if (!("publisher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publisher"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("limited" in $$source)) {
            /**
             * true = relies on Webview/Extension Host, limited functionality
             * @member
             * @type {boolean}
             */
            this["limited"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Extension}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Extension(/** @type {Partial<Extension>} */($$parsedSource));
    }
}

/**
 * ExtensionContributes holds the parsed contributes from a VSIX package.json.
 */
export class ExtensionContributes {
    /**
     * Creates a new ExtensionContributes instance.
     * @param {Partial<ExtensionContributes>} [$$source = {}] - The source object to create the ExtensionContributes.
     */
    constructor($$source = {}) {
        if (!("themes" in $$source)) {
            /**
             * @member
             * @type {ThemeContrib[]}
             */
            this["themes"] = [];
        }
        if (!("languages" in $$source)) {
            /**
             * @member
             * @type {LanguageContrib[]}
             */
            this["languages"] = [];
        }
        if (!("grammars" in $$source)) {
            /**
             * @member
             * @type {GrammarContrib[]}
             */
            this["grammars"] = [];
        }
        if (!("snippets" in $$source)) {
            /**
             * @member
             * @type {SnippetContrib[]}
             */
            this["snippets"] = [];
        }
        if (!("lspCmd" in $$source)) {
            /**
             * non-empty if a known LSP command was detected
             * @member
             * @type {string[]}
             */
            this["lspCmd"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionContributes instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtensionContributes}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField0_0($$parsedSource["themes"]);
        }
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField1_0($$parsedSource["languages"]);
        }
        if ("grammars" in $$parsedSource) {
            $$parsedSource["grammars"] = $$createField2_0($$parsedSource["grammars"]);
        }
        if ("snippets" in $$parsedSource) {
            $$parsedSource["snippets"] = $$createField3_0($$parsedSource["snippets"]);
        }
        if ("lspCmd" in $$parsedSource) {
            $$parsedSource["lspCmd"] = $$createField4_0($$parsedSource["lspCmd"]);
        }
        return new ExtensionContributes(/** @type {Partial<ExtensionContributes>} */($$parsedSource));
    }
}

/**
 * GrammarContrib is one entry under contributes.grammars.
 */
export class GrammarContrib {
    /**
     * Creates a new GrammarContrib instance.
     * @param {Partial<GrammarContrib>} [$$source = {}] - The source object to create the GrammarContrib.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("scopeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scopeName"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * raw JSON of .tmLanguage.json (plist grammars skipped)
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrammarContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GrammarContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GrammarContrib(/** @type {Partial<GrammarContrib>} */($$parsedSource));
    }
}

/**
 * LanguageContrib is one entry under contributes.languages.
 */
export class LanguageContrib {
    /**
     * Creates a new LanguageContrib instance.
     * @param {Partial<LanguageContrib>} [$$source = {}] - The source object to create the LanguageContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }
        if (!("filenames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["filenames"] = [];
        }
        if (!("configuration" in $$source)) {
            /**
             * raw JSON of language-configuration.json
             * @member
             * @type {string}
             */
            this["configuration"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LanguageContrib}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        if ("filenames" in $$parsedSource) {
            $$parsedSource["filenames"] = $$createField2_0($$parsedSource["filenames"]);
        }
        return new LanguageContrib(/** @type {Partial<LanguageContrib>} */($$parsedSource));
    }
}

/**
 * SnippetContrib is one entry under contributes.snippets.
 */
export class SnippetContrib {
    /**
     * Creates a new SnippetContrib instance.
     * @param {Partial<SnippetContrib>} [$$source = {}] - The source object to create the SnippetContrib.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * raw JSON of .code-snippets file
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnippetContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnippetContrib(/** @type {Partial<SnippetContrib>} */($$parsedSource));
    }
}

/**
 * ThemeContrib is one entry under contributes.themes.
 */
export class ThemeContrib {
    /**
     * Creates a new ThemeContrib instance.
     * @param {Partial<ThemeContrib>} [$$source = {}] - The source object to create the ThemeContrib.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("uiTheme" in $$source)) {
            /**
             * "vs", "vs-dark", "hc-black"
             * @member
             * @type {string}
             */
            this["uiTheme"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * raw JSON content of the theme file
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeContrib(/** @type {Partial<ThemeContrib>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ThemeContrib.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = LanguageContrib.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = GrammarContrib.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SnippetContrib.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
