// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides extension management functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetExtensionContributes parses the installed extension's package.json and returns
 * all statically-applicable contributions (themes, grammars, language configs, snippets).
 * @param {string} publisher
 * @param {string} name
 * @returns {$CancellablePromise<$models.ExtensionContributes | null>}
 */
export function GetExtensionContributes(publisher, name) {
    return $Call.ByID(4269795072, publisher, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetExtensionIcon returns the base64-encoded icon for an installed extension, or empty string
 * @param {string} publisher
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetExtensionIcon(publisher, name) {
    return $Call.ByID(2175814609, publisher, name);
}

/**
 * GetExtensionsDir returns the extensions directory path
 * @returns {$CancellablePromise<string>}
 */
export function GetExtensionsDir() {
    return $Call.ByID(3872533640);
}

/**
 * GetInstalledExtensions returns list of installed extensions
 * @returns {$CancellablePromise<$models.Extension[]>}
 */
export function GetInstalledExtensions() {
    return $Call.ByID(447222625).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InstallExtension installs an extension from Open VSX marketplace
 * @param {string} publisher
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function InstallExtension(publisher, name) {
    return $Call.ByID(2269302045, publisher, name);
}

/**
 * InstallLocalVSIX installs an extension from a local .vsix file path
 * @param {string} vsixPath
 * @returns {$CancellablePromise<void>}
 */
export function InstallLocalVSIX(vsixPath) {
    return $Call.ByID(2600665589, vsixPath);
}

/**
 * SearchExtensions searches for extensions in Open VSX marketplace
 * @param {string} query
 * @returns {$CancellablePromise<$models.Extension[]>}
 */
export function SearchExtensions(query) {
    return $Call.ByID(331717839, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ServeExtensionAsset serves a static asset file from an installed extension.
 * assetPath format: "publisher.name/relative/path/to/file"
 * @param {string} assetPath
 * @returns {$CancellablePromise<[string, string]>}
 */
export function ServeExtensionAsset(assetPath) {
    return $Call.ByID(1963557495, assetPath).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    }));
}

/**
 * UninstallExtension removes an installed extension
 * @param {string} publisher
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UninstallExtension(publisher, name) {
    return $Call.ByID(437355990, publisher, name);
}

// Private type creation functions
const $$createType0 = $models.ExtensionContributes.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Extension.createFrom;
const $$createType3 = $Create.Array($$createType2);
