// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DetectResult describes a detected project environment.
 */
export class DetectResult {
    /**
     * Creates a new DetectResult instance.
     * @param {Partial<DetectResult>} [$$source = {}] - The source object to create the DetectResult.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("setupCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["setupCmd"] = "";
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectResult(/** @type {Partial<DetectResult>} */($$parsedSource));
    }
}
