// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides project detection and setup.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProject creates a new project directory and returns its absolute path.
 * @param {string} parentDir
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateProject(parentDir, name) {
    return $Call.ByID(1130003266, parentDir, name);
}

/**
 * DetectProjectTypes scans a directory and returns detected + all available project types.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.DetectResult[]>}
 */
export function DetectProjectTypes(dirPath) {
    return $Call.ByID(3923375740, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RunSetup executes the setup command for a given project type in the specified directory.
 * Returns combined stdout+stderr output.
 * @param {string} dirPath
 * @param {string} projectType
 * @returns {$CancellablePromise<string>}
 */
export function RunSetup(dirPath, projectType) {
    return $Call.ByID(2866641107, dirPath, projectType);
}

// Private type creation functions
const $$createType0 = $models.DetectResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
