// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const AuthType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AuthPassword: "password",
    AuthKey: "key",
};

export class DeployConfig {
    /**
     * Creates a new DeployConfig instance.
     * @param {Partial<DeployConfig>} [$$source = {}] - The source object to create the DeployConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {DeployType}
             */
            this["type"] = DeployType.$zero;
        }
        if (!("serverIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["serverIds"] = [];
        }
        if (!("buildCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildCmd"] = "";
        }
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("remoteDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteDir"] = "";
        }
        if (!("script" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["script"] = "";
        }
        if (!("dockerImage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerImage"] = "";
        }
        if (!("dockerfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dockerfile"] = "";
        }
        if (!("registryURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["registryURL"] = "";
        }
        if (!("k8sManifest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["k8sManifest"] = "";
        }
        if (!("k8sNamespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["k8sNamespace"] = "";
        }
        if (!("k8sContext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["k8sContext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serverIds" in $$parsedSource) {
            $$parsedSource["serverIds"] = $$createField3_0($$parsedSource["serverIds"]);
        }
        return new DeployConfig(/** @type {Partial<DeployConfig>} */($$parsedSource));
    }
}

export class DeployTask {
    /**
     * Creates a new DeployTask instance.
     * @param {Partial<DeployTask>} [$$source = {}] - The source object to create the DeployTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("configId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configId"] = "";
        }
        if (!("configName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configName"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployTask(/** @type {Partial<DeployTask>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const DeployType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DeployShell: "shell",
    DeployDocker: "docker",
    DeployK8s: "k8s",
};

export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("authType" in $$source)) {
            /**
             * @member
             * @type {AuthType}
             */
            this["authType"] = AuthType.$zero;
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("keyPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyPath"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusIdle: "idle",
    StatusBuilding: "building",
    StatusUploading: "uploading",
    StatusDeploying: "deploying",
    StatusDone: "done",
    StatusError: "error",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
