// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.DeployConfig} cfg
 * @returns {$CancellablePromise<$models.DeployConfig>}
 */
export function AddConfig(cfg) {
    return $Call.ByID(421417830, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<$models.ServerConfig>}
 */
export function AddServer(cfg) {
    return $Call.ByID(4001176691, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} configID
 * @returns {$CancellablePromise<string>}
 */
export function Deploy(configID) {
    return $Call.ByID(1641747770, configID);
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.DeployTask | null>}
 */
export function GetTask(taskID) {
    return $Call.ByID(2001649634, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DeployConfig[]>}
 */
export function ListConfigs() {
    return $Call.ByID(550310420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ServerConfig[]>}
 */
export function ListServers() {
    return $Call.ByID(2329018363).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DeployTask[]>}
 */
export function ListTasks() {
    return $Call.ByID(397232869).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConfig(id) {
    return $Call.ByID(981732963, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveServer(id) {
    return $Call.ByID(871568166, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(id) {
    return $Call.ByID(3362995653, id);
}

/**
 * @param {$models.DeployConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(cfg) {
    return $Call.ByID(311330590, cfg);
}

/**
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateServer(cfg) {
    return $Call.ByID(1939706587, cfg);
}

// Private type creation functions
const $$createType0 = $models.DeployConfig.createFrom;
const $$createType1 = $models.ServerConfig.createFrom;
const $$createType2 = $models.DeployTask.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = $Create.Array($$createType2);
